# Generated by Django 4.1 on 2022-09-04 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0003_rename_category_categorymodel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AirlineModel',
            fields=[
                ('id', models.CharField(max_length=8, primary_key=True, serialize=False, unique=True)),
                ('From', models.TextField(max_length=15)),
                ('To', models.TextField(max_length=15)),
                ('Departing_Date', models.DateField()),
                ('Returning_Date', models.DateField()),
                ('Class', models.CharField(max_length=15)),
            ],
        ),
    ]
