# Generated by Django 4.1 on 2022-09-04 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0004_airlinemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Flightno', models.TextField(max_length=10)),
                ('DepartureDate', models.DateField()),
                ('Origin', models.TextField(max_length=20)),
                ('Destination', models.TextField(max_length=20)),
            ],
        ),
    ]
