# Generated by Django 4.1 on 2022-09-04 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0005_statusmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='CargoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Origin', models.TextField(max_length=20)),
                ('Destination', models.TextField(max_length=20)),
                ('Date', models.DateField()),
                ('Goods_Description', models.TextField()),
                ('Weight', models.IntegerField()),
                ('Product', models.TextField(max_length=30)),
            ],
        ),
    ]
