# Generated by Django 4.1 on 2022-09-05 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0006_cargomodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Booking_id', models.TextField(max_length=8)),
                ('Firstname', models.TextField(max_length=25)),
                ('Lastname', models.TextField(max_length=10)),
                ('Mobile_number', models.CharField(max_length=12)),
            ],
        ),
    ]
