# Generated by Django 4.1 on 2022-09-05 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0007_bookingmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pickup', models.TextField(max_length=20)),
                ('Dropoff', models.TextField(max_length=20)),
                ('PickupDate', models.DateField()),
                ('PickupTime', models.TimeField()),
            ],
        ),
    ]
